DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS MOVIE;
CREATE TABLE CUSTOMER(
   ID INT  AUTO_INCREMENT  PRIMARY KEY,
   NAME VARCHAR(250) NOT NULL ,
   INCOME INT,
   CREDIT_SCORE INT
);


CREATE TABLE employee(
   ID INT  AUTO_INCREMENT  PRIMARY KEY,
   name VARCHAR(250) NOT NULL ,
   email VARCHAR(250) NOT NULL ,
  headline VARCHAR(250) NOT NULL ,
  phone VARCHAR(250) NOT NULL 
);

CREATE TABLE USER(
   ID INT  AUTO_INCREMENT  PRIMARY KEY,
   NAME VARCHAR(250) NOT NULL,
   EMAIL VARCHAR(250) NOT NULL     
);

CREATE TABLE MOVIE(
   ID INT  AUTO_INCREMENT  PRIMARY KEY,
   TITLE VARCHAR(250) NOT NULL,
   RATING INT     
);

CREATE TABLE change_requests (
    id BIGINT PRIMARY KEY,
    cr_number VARCHAR(50) NOT NULL,
    creation_date_time TIMESTAMP NOT NULL,
    created_by VARCHAR(50) NOT NULL,
    account_group VARCHAR(100) NOT NULL
);

CREATE TABLE CUSTOMER_REVIEW (
   ID INT  AUTO_INCREMENT  PRIMARY KEY,
   REVIEW VARCHAR(250) NOT NULL,
      
);


