DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS USER;
CREATE TABLE CUSTOMER(
   ID INT  AUTO_INCREMENT  PRIMARY KEY,
   NAME VARCHAR(250) NOT NULL ,
   INCOME INT,
   CREDIT_SCORE INT
);


CREATE TABLE employee(
   ID INT  AUTO_INCREMENT  PRIMARY KEY,
   name VARCHAR(250) NOT NULL ,
   email VARCHAR(250) NOT NULL ,
  headline VARCHAR(250) NOT NULL ,
  phone VARCHAR(250) NOT NULL 
);

CREATE TABLE USER(
   ID INT  AUTO_INCREMENT  PRIMARY KEY,
   NAME VARCHAR(250) NOT NULL,
   EMAIL VARCHAR(250) NOT NULL     
);
